name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^2.6.1
  flex_color_scheme: ^8.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  chopper: ^8.3.0
  utils:
    path: ../utils
  shared_prefs: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  chopper_generator: ^8.2.0


flutter:
  uses-material-design: true
