name: utils
description: A generic interface for utils
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  dart_jsonwebtoken: ^3.2.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.6.1
  json_serializable: ^6.10.0
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
